name: "Build Win app"
description: "Builds the application with Qt on various platforms"
inputs:
  with-package:
    description: "Enable or disable packaging"
    required: true
    default: true
  qt-version:
    description: "Qt version"
    required: false
    default: "5.15.2"
runs:
  using: "composite"
  steps:
    # - name: Set up MinGW
    #   if: matrix.os == 'windows-latest'
    #   uses: egor-tensin/setup-mingw@v2.2.0
    #   with:
    #     version: 12.2.0 
    #     arch: x86_64

    - name: Install Qt and dependencies on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      shell: pwsh
      run: |
        python -m pip install aqtinstall
        aqt install-qt windows desktop 5.15.2 win64_mingw81
        $env:PATH="$env:GITHUB_WORKSPACE/5.15.2/mingw81_64/bin;$env:PATH"
        D:\a\qml-parser\qml-parser\5.15.2\mingw81_64\bin\qmake.exe -config release
        mingw32-make clean
        mingw32-make
        windeployqt dist\qml-parser.exe -no-plugins -verbose=1
