name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            binPath: dist\qml-parser.exe
          - os: ubuntu-20.04
            platform: linux
            binPath: dist/qml-parser
          - os: macos-13
            platform: darwin
            binPath: dist/qml-parser.app/Contents/MacOS/qml-parser

    steps:
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build app
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ./.github/actions/winbuild

      - name: Build app for other platforms
        if: ${{ matrix.os != 'windows-latest' }}
        uses: ./.github/actions/build
        with:
          with-package: false

      - uses: thedoctor0/zip-release@master
        with:
          directory: dist
          filename: ${{ matrix.platform }}.zip

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: dist/${{ matrix.platform }}.zip
